### ISSUE TITLE
Write a better README.md

### ISSUE THREAD

**Issue by Chaitya62** [Chaitya62/ProCookbook#24]
Currently, the readme.md is just a list of algorithms, but as I want this repository to be a python package in the future. A better readme, which explains that and what is in the repository is necessary.

**Comment by mbbroberg** [comment]
Hey @Chaitya62! I'm interested in helping out there. Based on what I see, I might recommend:

```
## Overview

### What this is
### What this isn't 

## How to Get Involved
## Glossary
## Resources
```

How's that sound? If it does sound good, could you talk about what your goal is for the project?

Cheers and happy Hacktoberfest 🎃

**Comment by Chaitya62** [comment]
@mbbroberg  Hey, Sound like a great idea. So as I mention in the readme 

> This project started as my curiosity to understand the inner workings of the algorithms and data structure. 

But,  why stop there, so now I am thinking of converting all the C++ code into a python library by wrapping it in python. Now, as far as the vision for this projects. I would like it to be a one-stop solution for all algorithms and data structure ever needed.  Thanks for volunteering to help me out, also please let me know what you think about my vision for the project.

**Comment by pydevsg** [comment]
Hi @Chaitya62  I can help you out with your vision project as being a Python Developer.
Here's how I can help you
1.Converting all the C++ code to Python.
2. Writing all the basics of Python Data Structure in Python 3 version .
I am willing to work here if you allow me so.

**Comment by Chaitya62** [comment]
@pydevsg Hey, I appreciate your willingness to help, but you seem to have misunderstood a few things. I don't want to convert the C++ code to Python, but just wrap it in python ( look at Python-C API to actually understand what I mean ). I guess that's the reason I need a better Readme first. Check the issue #23 to see the task that I think are necessary. Again thanks for showing your interest.
