### ISSUE TITLE
Add resources to beside the algorithms 

### ISSUE THREAD

**Issue by Chaitya62** [Chaitya62/ProCookbook#3]
Add usefull resources  which help in understanding  and implementing  the algorithms

**Comment by AllanNozomu** [comment]
Do you want problems, code implementation, and some information resources? Should I add it in the README?

**Comment by Chaitya62** [comment]
@Allan resources

**Comment by Chaitya62** [comment]
@Allan Yes resources  and you can add it in the readme file
